### ISSUE TITLE
Navigation menu

### ISSUE THREAD

**Issue by BonsaiOfHappiness** [tradity/tradity-client#107] opened 2017-01-21 12:43 UTC

**Comment by BonsaiOfHappiness** [comment] 2017-01-21 12:45
Comments after review:

- [ ] If "active" menu point still close menu

**Comment by nhaesler** [comment] 2017-01-21 12:47
Can you explain that comment?

Tried to reach you on Slack btw

**Comment by nhaesler** [comment] 2017-01-23 15:09
@BonsaiOfHappiness

**Comment by BonsaiOfHappiness** [comment] 2017-01-23 20:05
Mh, I'll tell you next time we speak :D

**Comment by nhaesler** [comment] 2017-02-11 22:32
@BonsaiOfHappiness You didn't actually tell me the next we spoke :P
Also probably a duplicate of #101.

**Comment by BonsaiOfHappiness** [comment] 2017-02-12 08:14
Let's ignore this for a while. It's not a "major bug" - Jakob and I will check for it again after the next update of dev.

**Comment by BonsaiOfHappiness** [comment] 2017-02-12 16:19
@raubja Could you please show the steps to get to the navigation menu bug (orange link thingy)

**Comment by nhaesler** [comment] 2017-02-14 20:10
That turned out to be a non-issue. Closing this in favor of #99.

**Closed by nhaesler** 2017-02-14 20:10 UTC
